### ISSUE TITLE
this package duplicates built-in sw_vers tool functionality

### ISSUE THREAD

**Issue by miniak** [sindresorhus/macos-version-cli#1]
There is no reason to implement this in JavaScript, you can use `sw_vers -productVersion` to get the same information. Also the tool from Apple is 10x faster.

```
$ time macos-version 
10.13.6

real	0m0.143s
user	0m0.111s
sys	0m0.030s

$ time sw_vers -productVersion
10.13.6

real	0m0.014s
user	0m0.005s
sys	0m0.007s
```

**Comment by sindresorhus** [comment]
So don't use it then. I made it because I can never remember that command. I also plan to add additional functionality in the future, like ability to assert a minimum macOS version.
